# Generated by Django 5.2.4 on 2025-07-17 17:21

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='团队名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_personal_space', models.BooleanField(default=False, verbose_name='是否为个人空间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('planning', '计划中'), ('active', '进行中'), ('completed', '已完成')], default='planning', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='knowledge_project.team', verbose_name='所属团队')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('editor', '编辑者'), ('viewer', '查看者')], default='viewer', max_length=10, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='knowledge_project.team', verbose_name='团队')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '团队成员关系',
                'verbose_name_plural': '团队成员关系',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='笔记标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='笔记内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='knowledge_project.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '知识笔记',
                'verbose_name_plural': '知识笔记',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='knowledge_p_created_91eb40_idx'), models.Index(fields=['project'], name='knowledge_p_project_cf38b7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_at'], name='knowledge_p_created_9f6c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_personal_space'], name='knowledge_p_is_pers_0f4bba_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='knowledge_p_created_8e8171_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='knowledge_p_status_b073db_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['team'], name='knowledge_p_team_id_5c0cfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('user', 'team')},
        ),
    ]
