# Generated by Django 4.2.23 on 2025-10-24 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import knowledge_project.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_code', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='激活码')),
                ('code_created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=knowledge_project.models.user_avatar_path, verbose_name='头像')),
                ('avatar_source', models.CharField(blank=True, max_length=32, verbose_name='头像来源')),
                ('bio', models.TextField(blank=True, max_length=160, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='个人简介')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=knowledge_project.models.user_avatar_path, verbose_name='主页横幅')),
                ('theme', models.JSONField(default=knowledge_project.models.default_theme_settings, help_text='存储用户界面主题配置', verbose_name='主题设置')),
                ('layout_mode', models.CharField(choices=[('default', '默认布局'), ('compact', '紧凑布局'), ('wide', '宽屏布局')], default='default', max_length=20, verbose_name='界面布局')),
                ('last_theme_update', models.DateTimeField(auto_now=True, help_text='记录用户最后修改主题的时间', verbose_name='最后主题更新时间')),
                ('allow_rich_bio', models.BooleanField(default=False, verbose_name='允许富文本简介')),
                ('likes_count', models.IntegerField(default=0, verbose_name='获赞数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('two_fa_enabled', models.BooleanField(default=False, verbose_name='启用两因素认证')),
                ('two_fa_method', models.CharField(blank=True, choices=[('totp', 'TOTP验证器'), ('email', '邮箱验证')], default='totp', max_length=10, verbose_name='2FA验证方式')),
                ('totp_secret', models.CharField(blank=True, help_text='用于 Google Authenticator 等 TOTP 应用的密钥', max_length=32, verbose_name='TOTP密钥')),
                ('backup_codes', models.JSONField(blank=True, default=list, help_text='用于 TOTP 设备丢失时的一次性备用码', verbose_name='备用验证码')),
                ('notify_login', models.BooleanField(default=True, help_text='账户登录时发送邮件通知', verbose_name='登录通知')),
                ('notify_password_change', models.BooleanField(default=True, help_text='密码修改时发送邮件通知', verbose_name='密码修改通知')),
                ('notify_password_reset', models.BooleanField(default=True, help_text='密码重置时发送邮件通知', verbose_name='密码重置通知')),
                ('notify_note_activities', models.BooleanField(default=False, help_text='笔记创建/修改/删除时发送邮件通知', verbose_name='笔记活动通知')),
                ('notify_profile_likes', models.BooleanField(default=True, help_text='个人空间或作品被点赞时发送邮件通知', verbose_name='点赞通知')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to='knowledge_project.profile', verbose_name='被点赞的用户资料')),
            ],
            options={
                'verbose_name': '点赞记录',
                'verbose_name_plural': '点赞记录',
                'indexes': [models.Index(fields=['liker', 'profile'], name='knowledge_p_liker_i_ea4deb_idx')],
                'unique_together': {('liker', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='笔记标题')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='笔记内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_notes', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='knowledge_project.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '知识笔记',
                'verbose_name_plural': '知识笔记',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='knowledge_p_created_91eb40_idx'), models.Index(fields=['author'], name='knowledge_p_author__06ba4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='文件名/资源名')),
                ('file', models.FileField(null=True, upload_to=knowledge_project.models.user_directory_path, verbose_name='上传文件')),
                ('asset_type', models.CharField(choices=[('file', '普通文件'), ('image', '图片'), ('code', '代码片段'), ('doc', '文档')], default='file', max_length=10, verbose_name='资源类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('image_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='文件哈希值')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '个人资产',
                'verbose_name_plural': '个人资产',
                'ordering': ['-uploaded_at'],
                'unique_together': {('uploader', 'image_hash')},
            },
        ),
    ]
