# Generated by Django 4.2.23 on 2025-08-03 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='note',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
