# Generated by Django 4.2.23 on 2025-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0002_add_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP地址')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='客户端指纹')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='尝试时间')),
                ('is_successful', models.BooleanField(default=False, verbose_name='是否成功')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
            ],
            options={
                'verbose_name': '密码重置尝试',
                'verbose_name_plural': '密码重置尝试',
                'indexes': [models.Index(fields=['email', 'attempted_at'], name='knowledge_p_email_704833_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='knowledge_p_ip_addr_48fcac_idx'), models.Index(fields=['fingerprint', 'attempted_at'], name='knowledge_p_fingerp_113a05_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaptchaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='验证码ID')),
                ('captcha_text', models.CharField(max_length=6, verbose_name='验证码文本')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '验证码会话',
                'verbose_name_plural': '验证码会话',
                'indexes': [models.Index(fields=['captcha_id'], name='knowledge_p_captcha_2b1b7a_idx'), models.Index(fields=['expires_at'], name='knowledge_p_expires_d008e0_idx'), models.Index(fields=['ip_address'], name='knowledge_p_ip_addr_f26c58_idx')],
            },
        ),
    ]
