# Generated by Django 4.2.23 on 2025-08-03 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0003_note_is_public_note_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名/资源名')),
                ('file', models.FileField(upload_to='assets/%Y/%m/%d/', verbose_name='上传文件')),
                ('asset_type', models.CharField(choices=[('file', '普通文件'), ('image', '图片'), ('code', '代码片段'), ('doc', '文档')], default='file', max_length=10, verbose_name='资源类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='knowledge_project.project', verbose_name='所属项目')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '项目资产',
                'verbose_name_plural': '项目资产',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
