# Generated by Django 4.2.23 on 2025-08-03 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import knowledge_project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0004_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('editor', '编辑者'), ('viewer', '查看者')], default='viewer', max_length=10, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
            options={
                'verbose_name': '项目成员关系',
                'verbose_name_plural': '项目成员关系',
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='knowledge_p_team_id_5c0cfa_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='is_personal_space',
            field=models.BooleanField(default=False, verbose_name='是否为个人空间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(upload_to=knowledge_project.models.user_directory_path, verbose_name='上传文件'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='激活码'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='code_created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_personal_space'], name='knowledge_p_is_pers_882e69_idx'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='knowledge_project.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='knowledge_project.ProjectMembership', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['user', 'project'], name='knowledge_p_user_id_8ea299_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['role'], name='knowledge_p_role_38bccc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('user', 'project')},
        ),
    ]
