# Generated by Django 4.2.23 on 2025-12-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0004_logindevice_loginnotification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptchaSession',
        ),
    ]
