# Generated by Django 4.2.23 on 2025-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0005_projectmembership_remove_team_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='文件名/资源名'),
        ),
    ]
