# Generated by Django 4.2.23 on 2025-12-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0005_delete_captchasession'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='查看次数'),
        ),
    ]
