# Generated by Django 4.2.23 on 2025-08-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0006_alter_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='笔记内容'),
        ),
    ]
