# Generated by Django 4.2.23 on 2026-01-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0006_note_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='toc',
            field=models.JSONField(blank=True, default=list, verbose_name='目录结构'),
        ),
    ]
