# Generated by Django 4.2.23 on 2025-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0007_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content_text',
            field=models.TextField(blank=True, editable=False, verbose_name='纯文本内容（供搜索）'),
        ),
    ]
