# Generated by Django 4.2.23 on 2025-08-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0008_note_content_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_personal_inbox',
            field=models.BooleanField(default=False, verbose_name='是否为随手笔记'),
        ),
        migrations.AlterField(
            model_name='note',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='knowledge_project.project', verbose_name='所属项目'),
        ),
    ]
