# Generated by Django 4.2.23 on 2026-01-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0008_folder_note_folder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='folder',
            new_name='knowledge_p_owner_i_644a36_idx',
            old_name='knowledge_p_owner_i_folder_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='knowledge_p_folder__1644de_idx',
            old_name='knowledge_p_folder__note_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='knowledge_p_is_tras_5356b2_idx',
            old_name='knowledge_p_trashed_note_idx',
        ),
        migrations.AddField(
            model_name='note',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_favorited'], name='knowledge_p_is_favo_b39e55_idx'),
        ),
    ]
