# Generated by Django 4.2.23 on 2025-08-05 13:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0009_project_is_personal_inbox_alter_note_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content_text',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='笔记内容'),
        ),
    ]
