# Generated by Django 4.2.23 on 2026-01-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0009_rename_knowledge_p_owner_i_folder_idx_knowledge_p_owner_i_644a36_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_secret',
            field=models.BooleanField(default=False, help_text='标记为保密的笔记需要2FA验证才能访问', verbose_name='保密笔记'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_secret'], name='knowledge_p_is_secr_fad420_idx'),
        ),
    ]
