# Generated by Django 4.2.23 on 2026-01-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0010_add_is_secret_to_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_vault_key',
            field=models.TextField(blank=True, help_text='Base64编码的AES加密DEK，用KEK加密', null=True, verbose_name='加密保险柜密钥'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vault_initialized',
            field=models.BooleanField(default=False, help_text='用户是否已初始化保险柜', verbose_name='保险柜已初始化'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vault_key_iv',
            field=models.TextField(blank=True, help_text='加密DEK时的初始化向量（Base64编码）', null=True, verbose_name='保险柜密钥IV'),
        ),
    ]
