# Generated by Django 4.2.23 on 2025-08-05 13:57

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0010_remove_note_content_text_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='笔记内容'),
        ),
    ]
