# Generated by Django 4.2.23 on 2026-02-01 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0011_profile_encrypted_vault_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_trashed',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='folder',
            name='original_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_children', to='knowledge_project.folder', verbose_name='删除前的父文件夹'),
        ),
        migrations.AddField(
            model_name='folder',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_trashed'], name='knowledge_p_is_tras_09ed9d_idx'),
        ),
    ]
