# Generated by Django 4.2.23 on 2026-02-08 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0012_folder_is_trashed_folder_original_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(db_index=True, max_length=150, verbose_name='用户/账号')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='来源IP')),
                ('action', models.CharField(choices=[('vault_fail', '保密柜失败'), ('login_fail', '登录失败'), ('ip_banned', 'IP封禁'), ('device_revoked', '设备信任撤销')], db_index=True, default='vault_fail', max_length=20, verbose_name='行为')),
                ('count', models.IntegerField(default=1, verbose_name='聚合频次')),
                ('details', models.TextField(blank=True, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
            options={
                'verbose_name': '安全访问日志',
                'verbose_name_plural': '安全访问日志',
                'indexes': [models.Index(fields=['user_identifier', 'ip_address', 'action'], name='knowledge_p_user_id_1113d0_idx'), models.Index(fields=['created_at'], name='knowledge_p_created_78d3e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='加密令牌')),
                ('user_agent', models.CharField(max_length=500, verbose_name='UA标识')),
                ('ip_address', models.GenericIPAddressField(verbose_name='首次IP')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最近IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='最后使用')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('fail_count', models.IntegerField(default=0, verbose_name='设备级失败计数')),
                ('is_revoked', models.BooleanField(db_index=True, default=False, verbose_name='已撤销')),
                ('revoked_reason', models.CharField(blank=True, max_length=100, verbose_name='撤销原因')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '信任设备',
                'verbose_name_plural': '信任设备',
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='knowledge_p_user_id_91fd9a_idx'), models.Index(fields=['expires_at'], name='knowledge_p_expires_503a0e_idx')],
            },
        ),
    ]
