# Generated by Django 4.2.23 on 2026-03-22 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0014_add_notecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='浏览时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='knowledge_project.note', verbose_name='笔记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '笔记浏览历史',
                'verbose_name_plural': '笔记浏览历史',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='knowledge_p_user_id_2f835b_idx')],
                'unique_together': {('user', 'note')},
            },
        ),
    ]
