# Generated by Django 4.2.23 on 2026-03-24 19:58

from django.db import migrations, models
import knowledge_project.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0016_message_messagepreference_userblocklist'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='knowledge_p_sender__19817c_idx',
            old_name='knowledge_p_sender__idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='knowledge_p_recipie_a89873_idx',
            old_name='knowledge_p_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='userblocklist',
            new_name='knowledge_p_user_id_328e21_idx',
            old_name='knowledge_p_user_id_idx',
        ),
        migrations.AlterField(
            model_name='messagepreference',
            name='allow_messages',
            field=models.BooleanField(default=False, verbose_name='允许接收私信'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to=knowledge_project.models.user_avatar_path, verbose_name='主页横幅'),
        ),
    ]
