# Generated by Django 4.2.23 on 2026-04-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0017_banner_image_to_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for_recipient',
            field=models.BooleanField(default=False, verbose_name='接收者已删除'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_sender',
            field=models.BooleanField(default=False, verbose_name='发送者已删除'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_recalled',
            field=models.BooleanField(default=False, verbose_name='已撤回'),
        ),
        migrations.AddField(
            model_name='message',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撤回时间'),
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾广告'), ('abuse', '辱骂骚扰'), ('porn', '色情低俗'), ('scam', '诈骗欺诈'), ('other', '其他')], max_length=20, verbose_name='原因')),
                ('detail', models.TextField(blank=True, max_length=1000, verbose_name='补充说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('dismissed', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='knowledge_project.message', verbose_name='关联消息')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='被举报者')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='举报者')),
            ],
            options={
                'verbose_name': '私信举报',
                'verbose_name_plural': '私信举报',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='knowledge_p_status_5b6c65_idx'), models.Index(fields=['reported_user'], name='knowledge_p_reporte_e39bf0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('is_muted', models.BooleanField(default=False, verbose_name='消息免打扰')),
                ('is_archived', models.BooleanField(default=False, verbose_name='已归档')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('disappearing_enabled', models.BooleanField(default=False, verbose_name='开启阅后即焚')),
                ('disappearing_ttl_seconds', models.IntegerField(default=86400, verbose_name='阅后即焚 TTL (秒)')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最后读取时间')),
                ('force_unread', models.BooleanField(default=False, verbose_name='手动标记未读')),
                ('cleared_before', models.DateTimeField(blank=True, null=True, verbose_name='清空时间（不显示此时间之前的消息）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='对方')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_settings', to=settings.AUTH_USER_MODEL, verbose_name='归属用户')),
            ],
            options={
                'verbose_name': '会话设置',
                'verbose_name_plural': '会话设置',
                'indexes': [models.Index(fields=['user', 'is_archived'], name='knowledge_p_user_id_2aafeb_idx'), models.Index(fields=['user', 'is_pinned'], name='knowledge_p_user_id_3e1caa_idx')],
                'unique_together': {('user', 'peer')},
            },
        ),
    ]
