# Generated by Django 4.2.23 on 2026-04-19 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0018_message_deleted_for_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepreference',
            name='last_email_notified_at',
            field=models.DateTimeField(blank=True, help_text='用于聚合邮件（同一对话 15 分钟内最多一封）', null=True, verbose_name='最后邮件通知时间'),
        ),
        migrations.AddField(
            model_name='profile',
            name='discoverable_by_email',
            field=models.BooleanField(default=False, help_text='关闭后即使输入完整邮箱也无法被搜索到', verbose_name='允许通过邮箱搜索到我'),
        ),
        migrations.AddField(
            model_name='profile',
            name='discoverable_by_username',
            field=models.BooleanField(default=False, help_text='关闭后即使输入完整用户名也无法被搜索到', verbose_name='允许通过用户名搜索到我'),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_code',
            field=models.CharField(blank=True, db_index=True, help_text='8 位随机字符串，用户可主动分享给朋友用于添加', max_length=12, null=True, unique=True, verbose_name='公开搜索短码'),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'indexes': [models.Index(fields=['follower', 'following'], name='knowledge_p_followe_123ec5_idx'), models.Index(fields=['following', '-created_at'], name='knowledge_p_followi_f7063b_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='NewConversationQuotaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发起时间')),
                ('turnstile_passed', models.BooleanField(default=False, verbose_name='本次是否通过了 Turnstile')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='对方')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_conv_quota_logs', to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
            ],
            options={
                'verbose_name': '新对话配额日志',
                'verbose_name_plural': '新对话配额日志',
                'indexes': [models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_9d848f_idx')],
            },
        ),
    ]
