# Generated by Django 4.2.23 on 2026-05-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0023_alter_messageattachment_attachment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('removed', '已违规删除'), ('dismissed', '已驳回误报')], default='pending', max_length=20, verbose_name='处理状态')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='举报原因')),
                ('detail', models.TextField(blank=True, max_length=1000, verbose_name='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='knowledge_project.messageattachment', verbose_name='关联附件')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '私信附件举报',
                'verbose_name_plural': '私信附件举报',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attachment', 'status'], name='knowledge_p_attachm_58c78e_idx'), models.Index(fields=['status', '-created_at'], name='knowledge_p_status_8f4cb4_idx'), models.Index(fields=['reporter', '-created_at'], name='knowledge_p_reporte_46bcc1_idx')],
            },
        ),
    ]
