# Generated by Django 4.2.23 on 2026-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0024_attachmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pending_purge_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划物理清理时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际物理清理时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='was_reported',
            field=models.BooleanField(default=False, verbose_name='是否曾被举报'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='was_reported',
            field=models.BooleanField(default=False, verbose_name='是否曾被举报'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['pending_purge_at'], name='knowledge_p_pending_9127da_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['was_reported'], name='knowledge_p_was_rep_2545ac_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['was_reported'], name='knowledge_p_was_rep_5cb8e0_idx'),
        ),
    ]
