# Generated by Django 4.2.23 on 2026-05-10 12:56

from django.db import migrations, models


def backfill_searchable_text(apps, schema_editor):
    Message = apps.get_model('knowledge_project', 'Message')
    Message.objects.filter(searchable_text='').update(searchable_text=models.F('content'))


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0025_message_pending_purge_at_message_purged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='searchable_text',
            field=models.TextField(blank=True, default='', verbose_name='搜索文本'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='消息内容'),
        ),
        migrations.RunPython(backfill_searchable_text, migrations.RunPython.noop),
    ]
