# Generated by Django 4.2.23 on 2026-06-08 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0033_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('removed', '已删除'), ('dismissed', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='举报原因')),
                ('detail', models.TextField(blank=True, max_length=1000, verbose_name='补充说明')),
                ('pending_dedup_key', models.CharField(blank=True, editable=False, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理备注')),
            ],
            options={
                'verbose_name': '评论举报',
                'verbose_name_plural': '评论举报',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('removed', '已下架'), ('dismissed', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('reason', models.CharField(blank=True, max_length=120, verbose_name='举报原因')),
                ('detail', models.TextField(blank=True, max_length=1000, verbose_name='补充说明')),
                ('pending_dedup_key', models.CharField(blank=True, editable=False, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理备注')),
            ],
            options={
                'verbose_name': '文章举报',
                'verbose_name_plural': '文章举报',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='report_type',
            field=models.CharField(choices=[('message', '私信举报'), ('attachment', '附件举报'), ('note', '文章举报'), ('comment', '评论举报')], max_length=20, verbose_name='工单类型'),
        ),
        migrations.AlterField(
            model_name='usersanction',
            name='source_report_type',
            field=models.CharField(blank=True, choices=[('message', '私信举报'), ('attachment', '附件举报'), ('note', '文章举报'), ('comment', '评论举报')], max_length=20, verbose_name='来源工单类型'),
        ),
        migrations.AddField(
            model_name='notereport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notereport',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='knowledge_project.note', verbose_name='关联文章'),
        ),
        migrations.AddField(
            model_name='notereport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='被举报用户'),
        ),
        migrations.AddField(
            model_name='notereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='举报人'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='knowledge_project.notecomment', verbose_name='关联评论'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to='knowledge_project.note', verbose_name='关联文章'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='被举报用户'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='举报人'),
        ),
        migrations.AddIndex(
            model_name='notereport',
            index=models.Index(fields=['note', 'status'], name='knowledge_p_note_id_5b63af_idx'),
        ),
        migrations.AddIndex(
            model_name='notereport',
            index=models.Index(fields=['status', '-created_at'], name='knowledge_p_status_fa622a_idx'),
        ),
        migrations.AddIndex(
            model_name='notereport',
            index=models.Index(fields=['reporter', '-created_at'], name='knowledge_p_reporte_b322f9_idx'),
        ),
        migrations.AddIndex(
            model_name='notereport',
            index=models.Index(fields=['reported_user'], name='knowledge_p_reporte_45dc07_idx'),
        ),
        migrations.AddConstraint(
            model_name='notereport',
            constraint=models.UniqueConstraint(fields=('note', 'reporter', 'pending_dedup_key'), name='uniq_pending_note_report_per_reporter'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['comment', 'status'], name='knowledge_p_comment_d35317_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['status', '-created_at'], name='knowledge_p_status_25a0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['reporter', '-created_at'], name='knowledge_p_reporte_17249c_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['reported_user'], name='knowledge_p_reporte_869c9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'reporter', 'pending_dedup_key'), name='uniq_pending_comment_report_per_reporter'),
        ),
    ]
