# Generated by Django 4.2.23 on 2026-06-08 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0036_message_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='举报证据快照'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='举报证据快照'),
        ),
        migrations.AddField(
            model_name='notereport',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='举报证据快照'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='reason',
            field=models.CharField(choices=[('spam', '垃圾广告'), ('abuse', '辱骂骚扰'), ('porn', '色情低俗'), ('scam', '诈骗欺诈'), ('privacy', '侵犯隐私'), ('illegal', '违法违规'), ('other', '其他')], default='other', max_length=120, verbose_name='举报原因'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reason',
            field=models.CharField(choices=[('spam', '垃圾广告'), ('abuse', '辱骂骚扰'), ('porn', '色情低俗'), ('scam', '诈骗欺诈'), ('privacy', '侵犯隐私'), ('illegal', '违法违规'), ('other', '其他')], max_length=20, verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='notereport',
            name='reason',
            field=models.CharField(choices=[('spam', '垃圾广告'), ('abuse', '辱骂骚扰'), ('porn', '色情低俗'), ('scam', '诈骗欺诈'), ('privacy', '侵犯隐私'), ('illegal', '违法违规'), ('other', '其他')], default='other', max_length=120, verbose_name='举报原因'),
        ),
        migrations.CreateModel(
            name='ModerationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='模板名称')),
                ('report_type', models.CharField(blank=True, choices=[('message', '私信举报'), ('attachment', '附件举报'), ('note', '文章举报'), ('comment', '评论举报')], max_length=20, verbose_name='适用举报类型')),
                ('decision', models.CharField(blank=True, choices=[('uphold', '举报成立'), ('dismiss', '驳回举报'), ('manual', '重新处置'), ('appeal', '申诉处理')], max_length=20, verbose_name='适用场景')),
                ('content', models.TextField(max_length=2000, verbose_name='模板内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '处置模板',
                'verbose_name_plural': '处置模板',
                'ordering': ['report_type', 'decision', 'title'],
                'indexes': [models.Index(fields=['is_active', 'report_type', 'decision'], name='mtemplate_lookup_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('report_received', '举报已收到'), ('report_resolved', '举报已处理'), ('sanction_applied', '用户处置'), ('sanction_revoked', '处置解除'), ('appeal_submitted', '申诉已提交'), ('appeal_resolved', '申诉已处理')], max_length=40, verbose_name='通知类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='内容')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='附加数据')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '用户通知',
                'verbose_name_plural': '用户通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='unotify_user_read_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=2000, verbose_name='申诉理由')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '申诉通过'), ('rejected', '申诉驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('resolution_note', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('sanction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='knowledge_project.usersanction', verbose_name='关联处置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_appeals', to=settings.AUTH_USER_MODEL, verbose_name='申诉用户')),
            ],
            options={
                'verbose_name': '处置申诉',
                'verbose_name_plural': '处置申诉',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='mappeal_status_idx'), models.Index(fields=['user', '-created_at'], name='mappeal_user_idx')],
            },
        ),
    ]
