# Generated by Django 4.2.23 on 2026-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0037_commentreport_evidence_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='编辑时间'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='已编辑'),
        ),
    ]
