# Generated by Django 4.2.23 on 2026-06-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0038_groupmessage_edited_at_groupmessage_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentreport',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='举报证据快照'),
        ),
        migrations.AlterField(
            model_name='attachmentreport',
            name='reason',
            field=models.CharField(choices=[('spam', '垃圾广告'), ('abuse', '辱骂骚扰'), ('porn', '色情低俗'), ('scam', '诈骗欺诈'), ('privacy', '侵犯隐私'), ('illegal', '违法违规'), ('other', '其他')], default='other', max_length=120, verbose_name='举报原因'),
        ),
    ]
