# Generated by Django 4.2.23 on 2026-06-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0043_group_management'),
        ('knowledge_project', '0043_rename_group_invite_link_indexes'),
    ]

    operations = [
    ]
