# Generated by Django 4.2.23 on 2026-06-12 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0044_merge_20260612_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(blank=True, default='', max_length=200, verbose_name='申请留言')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('rejection_reason', models.TextField(blank=True, default='', max_length=200, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '入群申请',
                'verbose_name_plural': '入群申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提及时间')),
            ],
            options={
                'verbose_name': '群组消息提及',
                'verbose_name_plural': '群组消息提及',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=20, verbose_name='表情符号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反应时间')),
            ],
            options={
                'verbose_name': '群组消息表情回应',
                'verbose_name_plural': '群组消息表情回应',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#409EFF', max_length=7, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '群组标签',
                'verbose_name_plural': '群组标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '群组标签关系',
                'verbose_name_plural': '群组标签关系',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='messagegroupauditlog',
            new_name='knowledge_p_group_i_b23fcd_idx',
            old_name='knowledge_p_group_i_6b66fc_idx',
        ),
        migrations.RenameIndex(
            model_name='messagegroupauditlog',
            new_name='knowledge_p_actor_i_2c5b32_idx',
            old_name='knowledge_p_actor_i_d60516_idx',
        ),
        migrations.RenameIndex(
            model_name='messagegroupauditlog',
            new_name='knowledge_p_target__d56f0d_idx',
            old_name='knowledge_p_target__1948c8_idx',
        ),
        migrations.RenameIndex(
            model_name='messagegroupauditlog',
            new_name='knowledge_p_action_abf666_idx',
            old_name='knowledge_p_action_744428_idx',
        ),
        migrations.RenameIndex(
            model_name='messagegroupban',
            new_name='knowledge_p_group_i_333aef_idx',
            old_name='knowledge_p_group_i_8f9b3a_idx',
        ),
        migrations.RenameIndex(
            model_name='messagegroupban',
            new_name='knowledge_p_expires_3901aa_idx',
            old_name='knowledge_p_expires_0c504e_idx',
        ),
        migrations.RenameIndex(
            model_name='messagegroupban',
            new_name='knowledge_p_revoked_9ed06f_idx',
            old_name='knowledge_p_revoked_3c7792_idx',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='knowledge_project.groupmessage', verbose_name='转发自消息'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='knowledge_project.groupmessage', verbose_name='回复消息'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='announcement_pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='公告置顶时间'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='announcement_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_group_announcements', to=settings.AUTH_USER_MODEL, verbose_name='公告更新者'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False, verbose_name='启用自动回复'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='auto_reply_text',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='自动回复文本'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='require_approval',
            field=models.BooleanField(default=False, verbose_name='需要入群审批'),
        ),
        migrations.AddField(
            model_name='grouptagrelation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='knowledge_project.messagegroup', verbose_name='群组'),
        ),
        migrations.AddField(
            model_name='grouptagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_relations', to='knowledge_project.grouptag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='grouptagrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tag_relations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='groupmessagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='knowledge_project.groupmessage', verbose_name='消息'),
        ),
        migrations.AddField(
            model_name='groupmessagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='groupmessagemention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mentions', to=settings.AUTH_USER_MODEL, verbose_name='被提及用户'),
        ),
        migrations.AddField(
            model_name='groupmessagemention',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='knowledge_project.groupmessage', verbose_name='消息'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='knowledge_project.messagegroup', verbose_name='群组'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='groupjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请用户'),
        ),
        migrations.AddIndex(
            model_name='grouptagrelation',
            index=models.Index(fields=['user', 'group'], name='knowledge_p_user_id_21597c_idx'),
        ),
        migrations.AddIndex(
            model_name='grouptagrelation',
            index=models.Index(fields=['group', 'tag'], name='knowledge_p_group_i_9350c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouptagrelation',
            unique_together={('user', 'group', 'tag')},
        ),
        migrations.AddIndex(
            model_name='groupmessagereaction',
            index=models.Index(fields=['message', 'emoji'], name='knowledge_p_message_be20ed_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereaction',
            index=models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_2fc1be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='groupmessagemention',
            index=models.Index(fields=['message'], name='knowledge_p_message_4435d7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagemention',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='knowledge_p_mention_209c94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagemention',
            unique_together={('message', 'mentioned_user')},
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'status', '-created_at'], name='knowledge_p_group_i_f134f5_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_95625a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('group', 'user', 'status')},
        ),
    ]
