# Generated by Django 4.2.23 on 2026-06-13 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0045_enhance_group_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='allow_member_mention_all',
            field=models.BooleanField(default=False, verbose_name='Allow members to mention everyone'),
        ),
        migrations.AddField(
            model_name='messagegroup',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in_groups', to='knowledge_project.groupmessage', verbose_name='Pinned group message'),
        ),
        migrations.CreateModel(
            name='MessageGroupInviteUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Used at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_use_records', to='knowledge_project.messagegroup', verbose_name='Group')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_records', to='knowledge_project.messagegroupinvitelink', verbose_name='Invite link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_group_invite_uses', to=settings.AUTH_USER_MODEL, verbose_name='Joined user')),
            ],
            options={
                'verbose_name': 'Group invite use',
                'verbose_name_plural': 'Group invite uses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invite', '-created_at'], name='knowledge_p_invite__caa477_idx'), models.Index(fields=['group', '-created_at'], name='knowledge_p_group_i_4c7509_idx'), models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_35c8df_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupAnnouncementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='Announcement')),
                ('pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited at')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_group_announcement_edits', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_history', to='knowledge_project.messagegroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group announcement history',
                'verbose_name_plural': 'Group announcement history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='knowledge_p_group_i_a7e7e6_idx'), models.Index(fields=['editor', '-created_at'], name='knowledge_p_editor__94349c_idx')],
            },
        ),
    ]
