# Generated by Django 4.2.23 on 2026-06-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0046_messagegroup_allow_member_mention_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='group_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge_project.groupmessage', verbose_name='关联群组消息'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['uploader', 'group_message'], name='knowledge_p_uploade_ec5560_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['group_message', 'created_at'], name='knowledge_p_group_m_25f857_idx'),
        ),
    ]
