# Generated by Django 4.2.23 on 2026-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0047_messageattachment_group_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepreference',
            name='email_mention_groups',
            field=models.ManyToManyField(blank=True, related_name='email_mention_preferences', to='knowledge_project.messagegroup', verbose_name='群@邮件通知群组'),
        ),
        migrations.AddField(
            model_name='messagepreference',
            name='last_group_mention_email_notified_at',
            field=models.DateTimeField(blank=True, help_text='用于抑制群@邮件通知频率', null=True, verbose_name='最后群@邮件通知时间'),
        ),
        migrations.AddField(
            model_name='messagepreference',
            name='notify_group_mentions_email',
            field=models.BooleanField(default=False, verbose_name='邮件通知群@提及'),
        ),
    ]
