# Generated by Django 4.2.23 on 2026-06-14 17:43

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0048_messagepreference_email_mention_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGroupAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True, verbose_name='Read at')),
            ],
            options={
                'verbose_name': 'Group announcement read',
                'verbose_name_plural': 'Group announcement reads',
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('email_changed', 'Email changed'), ('device_revoked', 'Login device revoked')], db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Security audit log',
                'verbose_name_plural': 'Security audit logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='logindevice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active session'),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revoked at'),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_login_devices', to=settings.AUTH_USER_MODEL, verbose_name='Revoked by'),
        ),
        migrations.AddField(
            model_name='logindevice',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Session key'),
        ),
        migrations.AddField(
            model_name='messagepreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, verbose_name='Quiet hours enabled'),
        ),
        migrations.AddField(
            model_name='messagepreference',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Quiet hours end'),
        ),
        migrations.AddField(
            model_name='messagepreference',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Quiet hours start'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_last_changed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last email change time'),
        ),
        migrations.AddIndex(
            model_name='logindevice',
            index=models.Index(fields=['user', 'is_active'], name='knowledge_p_user_id_4c985c_idx'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagegroupannouncementread',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='knowledge_project.messagegroupannouncementhistory', verbose_name='Announcement'),
        ),
        migrations.AddField(
            model_name='messagegroupannouncementread',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='knowledge_project.messagegroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='messagegroupannouncementread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_announcement_reads', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_b62207_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='knowledge_p_actor_i_30257b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['action', '-created_at'], name='knowledge_p_action_1a1904_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupannouncementread',
            index=models.Index(fields=['group', 'announcement'], name='knowledge_p_group_i_521af3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupannouncementread',
            index=models.Index(fields=['user', '-read_at'], name='knowledge_p_user_id_8c8eb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagegroupannouncementread',
            unique_together={('group', 'user', 'announcement')},
        ),
    ]
