# Generated by Django 4.2.23 on 2026-06-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_project', '0049_messagegroupannouncementread_securityauditlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagegroupannouncementhistory',
            options={'ordering': ['-pinned', '-updated_at', '-created_at'], 'verbose_name': 'Group announcement history', 'verbose_name_plural': 'Group announcement history'},
        ),
        migrations.RemoveIndex(
            model_name='messagegroupannouncementhistory',
            name='knowledge_p_group_i_a7e7e6_idx',
        ),
        migrations.AddField(
            model_name='messagegroupannouncementhistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='messagegroupannouncementhistory',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_record', to='knowledge_project.groupmessage', verbose_name='Announcement message'),
        ),
        migrations.AddField(
            model_name='messagegroupannouncementhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddIndex(
            model_name='messagegroupannouncementhistory',
            index=models.Index(fields=['group', 'deleted_at', '-pinned', '-updated_at'], name='knowledge_p_group_i_a3bb3f_idx'),
        ),
    ]
