# Generated by Django 4.2.23 on 2026-06-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_alter_commentreport_comment_alter_commentreport_note_and_more'),
        ('knowledge_project', '0057_alter_conversationsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.RemoveField(
                            model_name='folder',
                            name='original_parent',
                        ),
                        migrations.RemoveField(
                            model_name='folder',
                            name='owner',
                        ),
                        migrations.RemoveField(
                            model_name='folder',
                            name='parent',
                        ),
                        migrations.RemoveField(
                            model_name='note',
                            name='author',
                        ),
                        migrations.RemoveField(
                            model_name='note',
                            name='folder',
                        ),
                        migrations.RemoveField(
                            model_name='note',
                            name='last_modified_by',
                        ),
                        migrations.RemoveField(
                            model_name='note',
                            name='tags',
                        ),
                        migrations.AlterUniqueTogether(
                            name='noteasset',
                            unique_together=None,
                        ),
                        migrations.RemoveField(
                            model_name='noteasset',
                            name='asset',
                        ),
                        migrations.RemoveField(
                            model_name='noteasset',
                            name='note',
                        ),
                        migrations.RemoveField(
                            model_name='notecomment',
                            name='author',
                        ),
                        migrations.RemoveField(
                            model_name='notecomment',
                            name='note',
                        ),
                        migrations.RemoveField(
                            model_name='notecomment',
                            name='parent',
                        ),
                        migrations.AlterUniqueTogether(
                            name='notehistory',
                            unique_together=None,
                        ),
                        migrations.RemoveField(
                            model_name='notehistory',
                            name='note',
                        ),
                        migrations.RemoveField(
                            model_name='notehistory',
                            name='user',
                        ),
                        migrations.DeleteModel(
                            name='Asset',
                        ),
                        migrations.DeleteModel(
                            name='Folder',
                        ),
                        migrations.DeleteModel(
                            name='Note',
                        ),
                        migrations.DeleteModel(
                            name='NoteAsset',
                        ),
                        migrations.DeleteModel(
                            name='NoteComment',
                        ),
                        migrations.DeleteModel(
                            name='NoteHistory',
                        ),
                        migrations.DeleteModel(
                            name='Tag',
                        ),
            ],
        ),
    ]
