# Generated by Django 4.2.23 on 2026-07-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_duplicate_profilelike_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accesslog',
            name='knowledge_p_created_78d3e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='logindevice',
            name='knowledge_p_user_id_7475e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='knowledge_p_token_b56c5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='profilelike',
            name='profilelike_liker_profile_idx',
        ),
        migrations.RemoveIndex(
            model_name='trusteddevice',
            name='knowledge_p_expires_503a0e_idx',
        ),
    ]
