# Generated by Django 4.2.23 on 2026-07-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_accesslog_knowledge_p_created_78d3e5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('registration_code', '注册验证码'), ('email_change_code', '邮箱修改验证码'), ('password_change_code', '密码修改验证码'), ('password_reset', '密码重置'), ('login_2fa', '登录两步验证码'), ('admin_login_2fa', '管理后台两步验证码'), ('vault_code', '保密柜验证码'), ('verification_code', '其他验证码'), ('login_alert', '登录提醒'), ('security_alert', '安全提醒'), ('notification', '业务通知'), ('other', '其他邮件')], default='other', max_length=32, verbose_name='邮件类型')),
                ('status', models.CharField(choices=[('succeeded', '发送成功'), ('failed', '发送失败')], max_length=16, verbose_name='投递状态')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='主题')),
                ('recipient_count', models.PositiveSmallIntegerField(default=1, verbose_name='收件人数')),
                ('provider', models.CharField(blank=True, max_length=64, verbose_name='投递通道')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '邮件投递日志',
                'verbose_name_plural': '邮件投递日志',
                'db_table': 'accounts_emaildeliverylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounts_email_status_idx'), models.Index(fields=['category', '-created_at'], name='accounts_email_category_idx')],
            },
        ),
    ]
