# Generated by Django 4.2.23 on 2026-06-18 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import notes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_project', '0057_alter_conversationsettings_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.CreateModel(
                            name='Asset',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('name', models.CharField(blank=True, max_length=255, verbose_name='文件名/资源名')),
                                ('file', models.FileField(null=True, upload_to=notes.models.user_directory_path, verbose_name='上传文件')),
                                ('asset_type', models.CharField(choices=[('file', '普通文件'), ('image', '图片'), ('code', '代码片段'), ('doc', '文档')], default='file', max_length=10, verbose_name='资源类型')),
                                ('description', models.TextField(blank=True, verbose_name='描述')),
                                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                                ('image_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='文件哈希值')),
                                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                            ],
                            options={
                                'verbose_name': '个人资产',
                                'verbose_name_plural': '个人资产',
                                'db_table': 'knowledge_project_asset',
                                'ordering': ['-uploaded_at'],
                            },
                        ),
                        migrations.CreateModel(
                            name='Folder',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('name', models.CharField(max_length=100, verbose_name='文件夹名称')),
                                ('order', models.IntegerField(default=0, verbose_name='排序顺序')),
                                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                                ('is_trashed', models.BooleanField(default=False, verbose_name='已删除')),
                                ('trashed_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                                ('original_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_children', to='notes.folder', verbose_name='删除前的父文件夹')),
                                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notes.folder', verbose_name='父文件夹')),
                            ],
                            options={
                                'verbose_name': '文件夹',
                                'verbose_name_plural': '文件夹',
                                'db_table': 'knowledge_project_folder',
                                'ordering': ['order', 'name'],
                            },
                        ),
                        migrations.CreateModel(
                            name='Tag',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名')),
                            ],
                            options={
                                'verbose_name': '标签',
                                'verbose_name_plural': '标签',
                                'db_table': 'knowledge_project_tag',
                            },
                        ),
                        migrations.CreateModel(
                            name='Note',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('title', models.CharField(max_length=255, verbose_name='笔记标题')),
                                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='笔记内容')),
                                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                                ('views', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                                ('toc', models.JSONField(blank=True, default=list, verbose_name='目录结构')),
                                ('is_trashed', models.BooleanField(default=False, verbose_name='已删除')),
                                ('is_favorited', models.BooleanField(default=False, verbose_name='已收藏')),
                                ('is_secret', models.BooleanField(default=False, help_text='标记为保密的笔记需要2FA验证才能访问', verbose_name='保密笔记')),
                                ('trashed_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_in_folder', to='notes.folder', verbose_name='所属文件夹')),
                                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_notes', to=settings.AUTH_USER_MODEL, verbose_name='最后修改者')),
                                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='notes.tag', verbose_name='标签')),
                            ],
                            options={
                                'verbose_name': '知识笔记',
                                'verbose_name_plural': '知识笔记',
                                'db_table': 'knowledge_project_note',
                                'ordering': ['-created_at'],
                            },
                        ),
                        migrations.CreateModel(
                            name='NoteHistory',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='浏览时间')),
                                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='notes.note', verbose_name='笔记')),
                                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                            ],
                            options={
                                'verbose_name': '笔记浏览历史',
                                'verbose_name_plural': '笔记浏览历史',
                                'db_table': 'knowledge_project_notehistory',
                                'ordering': ['-viewed_at'],
                                'indexes': [models.Index(fields=['user', '-viewed_at'], name='knowledge_p_user_id_2f835b_idx'), models.Index(fields=['user', '-viewed_at'], name='notehistory_user_viewed_idx')],
                                'unique_together': {('user', 'note')},
                            },
                        ),
                        migrations.CreateModel(
                            name='NoteComment',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('content', models.TextField(max_length=2000, verbose_name='评论内容')),
                                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='notes.note', verbose_name='所属笔记')),
                                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.notecomment', verbose_name='回复的评论')),
                            ],
                            options={
                                'verbose_name': '笔记评论',
                                'verbose_name_plural': '笔记评论',
                                'db_table': 'knowledge_project_notecomment',
                                'ordering': ['created_at'],
                                'indexes': [models.Index(fields=['note', 'created_at'], name='notecomment_note_created_idx')],
                            },
                        ),
                        migrations.CreateModel(
                            name='NoteAsset',
                            fields=[
                                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                                ('created_at', models.DateTimeField(auto_now_add=True)),
                                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='notes.asset')),
                                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='notes.note')),
                            ],
                            options={
                                'verbose_name': 'Note asset link',
                                'verbose_name_plural': 'Note asset links',
                                'db_table': 'knowledge_project_noteasset',
                                'indexes': [models.Index(fields=['asset', 'note'], name='noteasset_asset_note_idx')],
                                'unique_together': {('note', 'asset')},
                            },
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(fields=['created_at'], name='knowledge_p_created_91eb40_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(fields=['author'], name='knowledge_p_author__06ba4b_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(fields=['folder'], name='knowledge_p_folder__1644de_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(fields=['is_trashed'], name='knowledge_p_is_tras_5356b2_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(fields=['is_favorited'], name='knowledge_p_is_favo_b39e55_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(fields=['is_secret'], name='knowledge_p_is_secr_fad420_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(fields=['author', 'is_trashed', 'is_secret'], name='note_author_trash_secret_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='note',
                            index=models.Index(condition=models.Q(('is_public', True)), fields=['is_public', '-updated_at'], name='note_public_updated_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='folder',
                            index=models.Index(fields=['owner', 'parent'], name='knowledge_p_owner_i_644a36_idx'),
                        ),
                        migrations.AddIndex(
                            model_name='folder',
                            index=models.Index(fields=['is_trashed'], name='knowledge_p_is_tras_09ed9d_idx'),
                        ),
                        migrations.AlterUniqueTogether(
                            name='asset',
                            unique_together={('uploader', 'image_hash')},
                        ),
            ],
        ),
    ]
