# Generated by Django 4.2.23 on 2026-07-13 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_remove_duplicate_notehistory_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Reader'), ('commenter', 'Commenter'), ('editor', 'Editor'), ('manager', 'Manager')], default='reader', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_note_collaborators', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_project_notecollaborator',
                'indexes': [models.Index(fields=['user', 'role'], name='notecollab_user_role_idx')],
                'unique_together': {('note', 'user')},
            },
        ),
    ]
