# Generated by Django 4.2.23 on 2026-07-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_collaboration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='note_public_updated_idx',
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_public', '-updated_at'], name='note_public_updated_idx'),
        ),
    ]
