# Generated by Django 4.2.23 on 2026-07-13 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0004_remove_note_note_public_updated_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('toc', models.JSONField(blank=True, default=list)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('restored', 'Restored')], default='updated', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_project_noterevision',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='notecomment',
            name='anchor_context',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='notecomment',
            name='anchor_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notecomment',
            name='anchor_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notecomment',
            name='anchor_text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='notecomment',
            index=models.Index(fields=['note', 'anchor_start'], name='notecomment_note_anchor_idx'),
        ),
        migrations.AddField(
            model_name='noterevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noterevision',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='notes.note'),
        ),
        migrations.AddIndex(
            model_name='noterevision',
            index=models.Index(fields=['note', '-created_at'], name='noterevision_note_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='noterevision',
            constraint=models.UniqueConstraint(fields=('note', 'version_number'), name='note_revision_unique_version'),
        ),
    ]
