# Generated by Django 4.2.23 on 2026-06-18 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import messaging.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_project', '0056_move_reports_to_moderation'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('searchable_text', models.TextField(blank=True, default='', verbose_name='搜索文本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_edited', models.BooleanField(default=False, verbose_name='已编辑')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='编辑时间')),
                ('is_recalled', models.BooleanField(default=False, verbose_name='已撤回')),
                ('recalled_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('was_reported', models.BooleanField(default=False, verbose_name='是否曾被举报')),
                ('forwarded_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='messaging.groupmessage', verbose_name='转发自消息')),
            ],
            options={
                'verbose_name': '群组消息',
                'verbose_name_plural': '群组消息',
                'db_table': 'knowledge_project_groupmessage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#409EFF', max_length=7, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '群组标签',
                'verbose_name_plural': '群组标签',
                'db_table': 'knowledge_project_grouptag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('searchable_text', models.TextField(blank=True, default='', verbose_name='搜索文本')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='读取时间')),
                ('deleted_for_sender', models.BooleanField(default=False, verbose_name='发送者已删除')),
                ('deleted_for_recipient', models.BooleanField(default=False, verbose_name='接收者已删除')),
                ('is_recalled', models.BooleanField(default=False, verbose_name='已撤回')),
                ('recalled_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('was_reported', models.BooleanField(default=False, verbose_name='是否曾被举报')),
                ('pending_purge_at', models.DateTimeField(blank=True, null=True, verbose_name='计划物理清理时间')),
                ('purged_at', models.DateTimeField(blank=True, null=True, verbose_name='实际物理清理时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '私信',
                'verbose_name_plural': '私信',
                'db_table': 'knowledge_project_message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='群组名称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='group_avatars/', verbose_name='群头像')),
                ('description', models.TextField(blank=True, default='', verbose_name='群简介')),
                ('announcement', models.TextField(blank=True, default='', verbose_name='群公告')),
                ('announcement_pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='公告置顶时间')),
                ('require_approval', models.BooleanField(default=False, verbose_name='需要入群审批')),
                ('allow_member_mention_all', models.BooleanField(default=False, verbose_name='Allow members to mention everyone')),
                ('auto_reply_enabled', models.BooleanField(default=False, verbose_name='启用自动回复')),
                ('auto_reply_text', models.TextField(blank=True, default='', max_length=500, verbose_name='自动回复文本')),
                ('mute_mode', models.CharField(choices=[('none', '不限制发言'), ('admins_only', '仅群主/管理员可发言')], default='none', max_length=32, verbose_name='发言模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('announcement_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_group_announcements', to=settings.AUTH_USER_MODEL, verbose_name='公告更新者')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_message_groups', to=settings.AUTH_USER_MODEL, verbose_name='群主')),
                ('pinned_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_in_groups', to='messaging.groupmessage', verbose_name='Pinned group message')),
            ],
            options={
                'verbose_name': '私信群组',
                'verbose_name_plural': '私信群组',
                'db_table': 'knowledge_project_messagegroup',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupAnnouncementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='Announcement')),
                ('pinned', models.BooleanField(default=False, verbose_name='Pinned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_group_announcement_edits', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_history', to='messaging.messagegroup', verbose_name='Group')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_record', to='messaging.groupmessage', verbose_name='Announcement message')),
            ],
            options={
                'verbose_name': 'Group announcement history',
                'verbose_name_plural': 'Group announcement history',
                'db_table': 'knowledge_project_messagegroupannouncementhistory',
                'ordering': ['-pinned', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=messaging.models.generate_group_invite_token, max_length=64, unique=True, verbose_name='邀请令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='最大使用次数')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='messaging.messagegroup', verbose_name='群组')),
            ],
            options={
                'verbose_name': '群组邀请链接',
                'verbose_name_plural': '群组邀请链接',
                'db_table': 'knowledge_project_messagegroupinvitelink',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='允许用户创建群组')),
                ('min_public_notes', models.PositiveIntegerField(default=10, verbose_name='公开文章数门槛')),
                ('min_followers', models.PositiveIntegerField(default=50, verbose_name='关注者数门槛')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '私信群组创建策略',
                'verbose_name_plural': '私信群组创建策略',
                'db_table': 'knowledge_project_messagegrouppolicy',
            },
        ),
        migrations.CreateModel(
            name='MessagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_messages', models.BooleanField(default=False, verbose_name='允许接收私信')),
                ('message_mode', models.CharField(choices=[('all', '所有已登录用户'), ('followers_only', '仅关注者'), ('following_only', '仅我关注的人'), ('disabled', '禁用私信')], default='all', max_length=20, verbose_name='私信模式')),
                ('show_read_status', models.BooleanField(default=True, verbose_name='显示已读状态')),
                ('auto_reply_enabled', models.BooleanField(default=False, verbose_name='启用自动回复')),
                ('auto_reply_text', models.TextField(blank=True, default='', max_length=500, verbose_name='自动回复内容')),
                ('notify_new_message', models.BooleanField(default=True, verbose_name='邮件通知新私信')),
                ('browser_new_message', models.BooleanField(default=False, verbose_name='浏览器通知新私信')),
                ('notify_group_mentions_email', models.BooleanField(default=False, verbose_name='邮件通知群@提及')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Quiet hours enabled')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet hours end')),
                ('last_email_notified_at', models.DateTimeField(blank=True, help_text='用于聚合邮件（同一对话 15 分钟内最多一封）', null=True, verbose_name='最后邮件通知时间')),
                ('last_group_mention_email_notified_at', models.DateTimeField(blank=True, help_text='用于抑制群@邮件通知频率', null=True, verbose_name='最后群@邮件通知时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email_mention_groups', models.ManyToManyField(blank=True, db_table='knowledge_project_messagepreference_email_mention_groups', related_name='email_mention_preferences', to='messaging.messagegroup', verbose_name='群@邮件通知群组')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '私信偏好设置',
                'verbose_name_plural': '私信偏好设置',
                'db_table': 'knowledge_project_messagepreference',
            },
        ),
        migrations.CreateModel(
            name='MessageGroupBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='封禁原因')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='封禁时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='解封时间')),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_message_group_bans', to=settings.AUTH_USER_MODEL, verbose_name='封禁操作者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='messaging.messagegroup', verbose_name='群组')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_message_group_bans', to=settings.AUTH_USER_MODEL, verbose_name='解封操作者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_group_bans', to=settings.AUTH_USER_MODEL, verbose_name='被封禁用户')),
            ],
            options={
                'verbose_name': '群组封禁记录',
                'verbose_name_plural': '群组封禁记录',
                'db_table': 'knowledge_project_messagegroupban',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('group_create', '创建群组'), ('group_update_profile', '更新群资料'), ('group_rename', '修改群名'), ('group_announcement_update', '更新群公告'), ('member_add', '添加成员'), ('member_remove', '移除成员'), ('member_role_change', '修改成员角色'), ('member_mute', '禁言成员'), ('member_unmute', '解除成员禁言'), ('group_mute_change', '修改全员禁言'), ('ownership_transfer', '转让群主'), ('invite_link_create', '创建邀请链接'), ('invite_link_revoke', '撤销邀请链接'), ('member_ban', '封禁成员'), ('member_unban', '解除封禁'), ('group_dissolve', '解散群组'), ('group_leave', '退出群组')], max_length=64, verbose_name='动作')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_group_audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='messaging.messagegroup', verbose_name='群组')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_group_audit_targets', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
            ],
            options={
                'verbose_name': '群组审计日志',
                'verbose_name_plural': '群组审计日志',
                'db_table': 'knowledge_project_messagegroupauditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True, verbose_name='Read at')),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='messaging.messagegroupannouncementhistory', verbose_name='Announcement')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='messaging.messagegroup', verbose_name='Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_announcement_reads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Group announcement read',
                'verbose_name_plural': 'Group announcement reads',
                'db_table': 'knowledge_project_messagegroupannouncementread',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=messaging.models.message_attachment_path, verbose_name='附件文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('attachment_type', models.CharField(choices=[('image', '图片'), ('audio', '语音'), ('video', '视频'), ('file', '文件')], default='file', max_length=10, verbose_name='附件类型')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME 类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('was_reported', models.BooleanField(default=False, verbose_name='是否曾被举报')),
                ('group_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.groupmessage', verbose_name='关联群组消息')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='关联私信')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '私信附件',
                'verbose_name_plural': '私信附件',
                'db_table': 'knowledge_project_messageattachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='messaging.messagegroup', verbose_name='群组')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_relations', to='messaging.grouptag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tag_relations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '群组标签关系',
                'verbose_name_plural': '群组标签关系',
                'db_table': 'knowledge_project_grouptagrelation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=20, verbose_name='表情符号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反应时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.groupmessage', verbose_name='消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_reactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '群组消息表情回应',
                'verbose_name_plural': '群组消息表情回应',
                'db_table': 'knowledge_project_groupmessagereaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提及时间')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mentions', to=settings.AUTH_USER_MODEL, verbose_name='被提及用户')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='messaging.groupmessage', verbose_name='消息')),
            ],
            options={
                'verbose_name': '群组消息提及',
                'verbose_name_plural': '群组消息提及',
                'db_table': 'knowledge_project_groupmessagemention',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessageDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='删除时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='messaging.groupmessage', verbose_name='群组消息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '群组消息删除记录',
                'verbose_name_plural': '群组消息删除记录',
                'db_table': 'knowledge_project_groupmessagedeletion',
            },
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.messagegroup', verbose_name='群组'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.groupmessage', verbose_name='回复消息'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者'),
        ),
        migrations.CreateModel(
            name='GroupJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(blank=True, default='', max_length=200, verbose_name='申请留言')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('rejection_reason', models.TextField(blank=True, default='', max_length=200, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='messaging.messagegroup', verbose_name='群组')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '入群申请',
                'verbose_name_plural': '入群申请',
                'db_table': 'knowledge_project_groupjoinrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('is_muted', models.BooleanField(default=False, verbose_name='消息免打扰')),
                ('is_archived', models.BooleanField(default=False, verbose_name='已归档')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('disappearing_enabled', models.BooleanField(default=False, verbose_name='开启阅后即焚')),
                ('disappearing_ttl_seconds', models.IntegerField(default=86400, verbose_name='阅后即焚 TTL (秒)')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最后读取时间')),
                ('force_unread', models.BooleanField(default=False, verbose_name='手动标记未读')),
                ('cleared_before', models.DateTimeField(blank=True, null=True, verbose_name='清空时间（不显示此时间之前的消息）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='对方')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_settings', to=settings.AUTH_USER_MODEL, verbose_name='归属用户')),
            ],
            options={
                'verbose_name': '会话设置',
                'verbose_name_plural': '会话设置',
                'db_table': 'knowledge_project_conversationsettings',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '用户关注',
                'verbose_name_plural': '用户关注',
                'db_table': 'knowledge_project_userfollow',
                'indexes': [models.Index(fields=['follower', 'following'], name='knowledge_p_followe_123ec5_idx'), models.Index(fields=['following', '-created_at'], name='knowledge_p_followi_f7063b_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='屏蔽原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='屏蔽时间')),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='被屏蔽用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL, verbose_name='屏蔽者')),
            ],
            options={
                'verbose_name': '用户屏蔽',
                'verbose_name_plural': '用户屏蔽',
                'db_table': 'knowledge_project_userblocklist',
                'indexes': [models.Index(fields=['user', 'blocked_user'], name='knowledge_p_user_id_328e21_idx')],
                'unique_together': {('user', 'blocked_user')},
            },
        ),
        migrations.CreateModel(
            name='NewConversationQuotaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发起时间')),
                ('turnstile_passed', models.BooleanField(default=False, verbose_name='本次是否通过了 Turnstile')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='对方')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_conv_quota_logs', to=settings.AUTH_USER_MODEL, verbose_name='发起者')),
            ],
            options={
                'verbose_name': '新对话配额日志',
                'verbose_name_plural': '新对话配额日志',
                'db_table': 'knowledge_project_newconversationquotalog',
                'indexes': [models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_9d848f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=12, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='退出时间')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最后读取时间')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='置顶时间')),
                ('is_muted', models.BooleanField(default=False, verbose_name='消息免打扰')),
                ('muted_until', models.DateTimeField(blank=True, null=True, verbose_name='群内禁言到期时间')),
                ('is_archived', models.BooleanField(default=False, verbose_name='已归档')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('force_unread', models.BooleanField(default=False, verbose_name='手动标记未读')),
                ('cleared_before', models.DateTimeField(blank=True, null=True, verbose_name='清空时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messaging.messagegroup', verbose_name='群组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '私信群组成员',
                'verbose_name_plural': '私信群组成员',
                'db_table': 'knowledge_project_messagegroupmember',
                'indexes': [models.Index(fields=['user', 'is_archived'], name='knowledge_p_user_id_3305a1_idx'), models.Index(fields=['group', 'left_at'], name='knowledge_p_group_i_af93f4_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageGroupInviteUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Used at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_use_records', to='messaging.messagegroup', verbose_name='Group')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_records', to='messaging.messagegroupinvitelink', verbose_name='Invite link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_group_invite_uses', to=settings.AUTH_USER_MODEL, verbose_name='Joined user')),
            ],
            options={
                'verbose_name': 'Group invite use',
                'verbose_name_plural': 'Group invite uses',
                'db_table': 'knowledge_project_messagegroupinviteuse',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invite', '-created_at'], name='knowledge_p_invite__caa477_idx'), models.Index(fields=['group', '-created_at'], name='knowledge_p_group_i_4c7509_idx'), models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_35c8df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='messagegroupinvitelink',
            index=models.Index(fields=['group', 'revoked_at'], name='knowledge_p_group_i_6012d6_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupinvitelink',
            index=models.Index(fields=['token'], name='knowledge_p_token_cf0d54_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupban',
            index=models.Index(fields=['group', 'user'], name='knowledge_p_group_i_333aef_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupban',
            index=models.Index(fields=['expires_at'], name='knowledge_p_expires_3901aa_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupban',
            index=models.Index(fields=['revoked_at'], name='knowledge_p_revoked_9ed06f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupauditlog',
            index=models.Index(fields=['group', '-created_at'], name='knowledge_p_group_i_b23fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupauditlog',
            index=models.Index(fields=['actor'], name='knowledge_p_actor_i_2c5b32_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupauditlog',
            index=models.Index(fields=['target_user'], name='knowledge_p_target__d56f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupauditlog',
            index=models.Index(fields=['action'], name='knowledge_p_action_abf666_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupannouncementread',
            index=models.Index(fields=['group', 'announcement'], name='knowledge_p_group_i_521af3_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupannouncementread',
            index=models.Index(fields=['user', '-read_at'], name='knowledge_p_user_id_8c8eb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagegroupannouncementread',
            unique_together={('group', 'user', 'announcement')},
        ),
        migrations.AddIndex(
            model_name='messagegroupannouncementhistory',
            index=models.Index(fields=['group', 'deleted_at', '-pinned', '-updated_at'], name='knowledge_p_group_i_a3bb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroupannouncementhistory',
            index=models.Index(fields=['editor', '-created_at'], name='knowledge_p_editor__94349c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroup',
            index=models.Index(fields=['owner', '-created_at'], name='knowledge_p_owner_i_e18715_idx'),
        ),
        migrations.AddIndex(
            model_name='messagegroup',
            index=models.Index(fields=['is_active'], name='knowledge_p_is_acti_be8860_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['uploader', 'message'], name='knowledge_p_uploade_dc88e7_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'created_at'], name='knowledge_p_message_9b22f9_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['uploader', 'group_message'], name='knowledge_p_uploade_ec5560_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['group_message', 'created_at'], name='knowledge_p_group_m_25f857_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['was_reported'], name='knowledge_p_was_rep_5cb8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', '-created_at'], name='knowledge_p_sender__19817c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read'], name='knowledge_p_recipie_a89873_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['pending_purge_at'], name='knowledge_p_pending_9127da_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['was_reported'], name='knowledge_p_was_rep_2545ac_idx'),
        ),
        migrations.AddIndex(
            model_name='grouptagrelation',
            index=models.Index(fields=['user', 'group'], name='knowledge_p_user_id_21597c_idx'),
        ),
        migrations.AddIndex(
            model_name='grouptagrelation',
            index=models.Index(fields=['group', 'tag'], name='knowledge_p_group_i_9350c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grouptagrelation',
            unique_together={('user', 'group', 'tag')},
        ),
        migrations.AddIndex(
            model_name='groupmessagereaction',
            index=models.Index(fields=['message', 'emoji'], name='knowledge_p_message_be20ed_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagereaction',
            index=models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_2fc1be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='groupmessagemention',
            index=models.Index(fields=['message'], name='knowledge_p_message_4435d7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessagemention',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='knowledge_p_mention_209c94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagemention',
            unique_together={('message', 'mentioned_user')},
        ),
        migrations.AddIndex(
            model_name='groupmessagedeletion',
            index=models.Index(fields=['user', 'message'], name='knowledge_p_user_id_3d38de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmessagedeletion',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', '-created_at'], name='knowledge_p_group_i_b3cef9_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['sender', '-created_at'], name='knowledge_p_sender__ee5817_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['was_reported'], name='knowledge_p_was_rep_3b4138_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['group', 'status', '-created_at'], name='knowledge_p_group_i_f134f5_idx'),
        ),
        migrations.AddIndex(
            model_name='groupjoinrequest',
            index=models.Index(fields=['user', '-created_at'], name='knowledge_p_user_id_95625a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('group', 'user', 'status')},
        ),
        migrations.AddIndex(
            model_name='conversationsettings',
            index=models.Index(fields=['user', 'is_archived'], name='knowledge_p_user_id_2aafeb_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsettings',
            index=models.Index(fields=['user', 'is_pinned'], name='knowledge_p_user_id_3e1caa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationsettings',
            unique_together={('user', 'peer')},
        ),
            ],
        ),
    ]
