# Generated by Django 4.2.23 on 2026-06-30 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_duplicate_notehistory_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0008_groupjoinrequest_source_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNoteShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Title snapshot')),
                ('was_public_at_share', models.BooleanField(default=False, verbose_name='Was public at share')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Shared at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_shares', to='messaging.messagegroup', verbose_name='Group')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_share', to='messaging.groupmessage', verbose_name='Group message')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_note_shares', to='notes.note', verbose_name='Note')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_group_notes', to=settings.AUTH_USER_MODEL, verbose_name='Shared by')),
            ],
            options={
                'verbose_name': 'Group note share',
                'verbose_name_plural': 'Group note shares',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='messaging_g_group_i_f79c84_idx'), models.Index(fields=['note', '-created_at'], name='messaging_g_note_id_0e3c77_idx'), models.Index(fields=['shared_by', '-created_at'], name='messaging_g_shared__bc84f4_idx'), models.Index(fields=['revoked_at'], name='messaging_g_revoked_22a006_idx')],
            },
        ),
    ]
