# Generated by Django 4.2.23 on 2026-07-05 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_remove_duplicate_notehistory_index'),
        ('messaging', '0010_message_edited_at_message_is_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectNoteShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Title snapshot')),
                ('was_public_at_share', models.BooleanField(default=False, verbose_name='Was public at share')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Shared at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked at')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_share', to='messaging.message', verbose_name='Message')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_note_shares', to='notes.note', verbose_name='Note')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_note_shares', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_direct_notes', to=settings.AUTH_USER_MODEL, verbose_name='Shared by')),
            ],
            options={
                'verbose_name': 'Direct note share',
                'verbose_name_plural': 'Direct note shares',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shared_by', '-created_at'], name='messaging_d_shared__948642_idx'), models.Index(fields=['recipient', '-created_at'], name='messaging_d_recipie_09ff59_idx'), models.Index(fields=['note', '-created_at'], name='messaging_d_note_id_5a57ea_idx'), models.Index(fields=['revoked_at'], name='messaging_d_revoked_e1f3e5_idx')],
            },
        ),
    ]
