# Generated by Django 4.2.23 on 2026-07-13 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0011_directnoteshare'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240, verbose_name='Question')),
                ('allow_multiple', models.BooleanField(default=False, verbose_name='Allow multiple choices')),
                ('closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Closes at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_polls', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='messaging.messagegroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group poll',
                'verbose_name_plural': 'Group polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160, verbose_name='Option')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='messaging.grouppoll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Group poll option',
                'verbose_name_plural': 'Group poll options',
                'ordering': ['position', 'id'],
                'unique_together': {('poll', 'position')},
            },
        ),
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', max_length=1200, verbose_name='Description')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Due at')),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_group_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_group_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='messaging.messagegroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group task',
                'verbose_name_plural': 'Group tasks',
                'ordering': ['status', 'due_at', '-created_at'],
                'indexes': [models.Index(fields=['group', 'status', 'due_at'], name='messaging_g_group_i_96be42_idx'), models.Index(fields=['assignee', 'status'], name='messaging_g_assigne_6fa547_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Voted at')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='messaging.grouppolloption', verbose_name='Option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='messaging.grouppoll', verbose_name='Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Group poll vote',
                'verbose_name_plural': 'Group poll votes',
                'indexes': [models.Index(fields=['poll', 'user'], name='messaging_g_poll_id_5b25f3_idx')],
                'unique_together': {('poll', 'option', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='grouppoll',
            index=models.Index(fields=['group', '-created_at'], name='messaging_g_group_i_a8564e_idx'),
        ),
        migrations.AddIndex(
            model_name='grouppoll',
            index=models.Index(fields=['closed_at', 'closes_at'], name='messaging_g_closed__2025e2_idx'),
        ),
    ]
