# Generated by Django 4.2.23 on 2026-07-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0012_group_work_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='directnoteshare',
            name='allow_forwarding',
            field=models.BooleanField(default=True, verbose_name='Allow forwarding'),
        ),
        migrations.AddField(
            model_name='groupnoteshare',
            name='allow_forwarding',
            field=models.BooleanField(default=True, verbose_name='Allow forwarding'),
        ),
        migrations.CreateModel(
            name='DirectNoteShareRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_read_at', models.DateTimeField(auto_now_add=True, verbose_name='First read at')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Last read at')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_note_share_reads', to=settings.AUTH_USER_MODEL, verbose_name='Reader')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='messaging.directnoteshare', verbose_name='Share')),
            ],
            options={
                'verbose_name': 'Direct note share read',
                'verbose_name_plural': 'Direct note share reads',
                'indexes': [
                    models.Index(fields=['share', '-last_read_at'], name='messaging_d_share_i_58ee7d_idx'),
                    models.Index(fields=['reader', '-last_read_at'], name='messaging_d_reader__b91a78_idx'),
                ],
                'unique_together': {('share', 'reader')},
            },
        ),
        migrations.CreateModel(
            name='GroupNoteShareRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_read_at', models.DateTimeField(auto_now_add=True, verbose_name='First read at')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='Last read at')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_note_share_reads', to=settings.AUTH_USER_MODEL, verbose_name='Reader')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='messaging.groupnoteshare', verbose_name='Share')),
            ],
            options={
                'verbose_name': 'Group note share read',
                'verbose_name_plural': 'Group note share reads',
                'indexes': [
                    models.Index(fields=['share', '-last_read_at'], name='messaging_g_share_i_59f6cc_idx'),
                    models.Index(fields=['reader', '-last_read_at'], name='messaging_g_reader__6bf4bb_idx'),
                ],
                'unique_together': {('share', 'reader')},
            },
        ),
    ]
