# Generated by Django 4.2.23 on 2026-07-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_note_share_read_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directnoteshareread',
            new_name='messaging_d_share_i_b17ba1_idx',
            old_name='messaging_d_share_i_58ee7d_idx',
        ),
        migrations.RenameIndex(
            model_name='directnoteshareread',
            new_name='messaging_d_reader__9a6ee6_idx',
            old_name='messaging_d_reader__b91a78_idx',
        ),
        migrations.RenameIndex(
            model_name='groupnoteshareread',
            new_name='messaging_g_share_i_214331_idx',
            old_name='messaging_g_share_i_59f6cc_idx',
        ),
        migrations.RenameIndex(
            model_name='groupnoteshareread',
            new_name='messaging_g_reader__88c272_idx',
            old_name='messaging_g_reader__6bf4bb_idx',
        ),
    ]
