# Generated by Django 4.2.23 on 2026-07-13 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0015_directmessagemute'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='visibility_scope',
            field=models.CharField(choices=[('all', 'All group members'), ('staff_and_target', 'Group managers and target member')], db_index=True, default='all', max_length=24, verbose_name='Visibility scope'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='visibility_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Visibility target user'),
        ),
        migrations.AddIndex(
            model_name='groupmessage',
            index=models.Index(fields=['group', 'visibility_scope', '-created_at'], name='messaging_g_group_i_f6a97b_idx'),
        ),
    ]
