# Generated by Django 4.2.23 on 2026-07-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_group_message_restricted_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='directnoteshareread',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
        migrations.AddField(
            model_name='groupnoteshareread',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='View count'),
        ),
    ]
