# Generated by Django 4.2.23 on 2026-07-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_directnoteshareread_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='directmessagemute',
            name='messaging_d_user_id_a03bb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagegroupinvitelink',
            name='knowledge_p_token_cf0d54_idx',
        ),
        migrations.RemoveIndex(
            model_name='userblocklist',
            name='messaging_u_user_id_05f0cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='userfollow',
            name='messaging_u_followe_d2fbcf_idx',
        ),
    ]
