# Generated by Django 4.2.23 on 2026-07-14 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0018_remove_directmessagemute_messaging_d_user_id_a03bb7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Saved at')),
                ('direct_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='messaging.message', verbose_name='Direct message')),
                ('group_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='messaging.groupmessage', verbose_name='Group message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Saved message',
                'verbose_name_plural': 'Saved messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='messaging_s_user_id_10d264_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='savedmessage',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('direct_message__isnull', False), ('group_message__isnull', True)), models.Q(('direct_message__isnull', True), ('group_message__isnull', False)), _connector='OR'), name='saved_message_has_one_source'),
        ),
        migrations.AddConstraint(
            model_name='savedmessage',
            constraint=models.UniqueConstraint(fields=('user', 'direct_message'), name='saved_direct_message_once'),
        ),
        migrations.AddConstraint(
            model_name='savedmessage',
            constraint=models.UniqueConstraint(fields=('user', 'group_message'), name='saved_group_message_once'),
        ),
    ]
