# Generated by Django 4.2.23 on 2026-06-18 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('moderation', '0006_rename_report_tables'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.AlterField(
            model_name='attachmentreport',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.messageattachment', verbose_name='关联附件'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='group_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='messaging.groupmessage', verbose_name='关联群组消息'),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='messaging.message', verbose_name='关联消息'),
        ),
            ],
        ),
    ]
