# Generated by Django 4.2.23 on 2026-06-18 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('moderation', '0007_alter_attachmentreport_attachment_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                        migrations.AlterField(
                            model_name='commentreport',
                            name='comment',
                            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='notes.notecomment', verbose_name='关联评论'),
                        ),
                        migrations.AlterField(
                            model_name='commentreport',
                            name='note',
                            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports', to='notes.note', verbose_name='关联文章'),
                        ),
                        migrations.AlterField(
                            model_name='notereport',
                            name='note',
                            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='notes.note', verbose_name='关联文章'),
                        ),
            ],
        ),
    ]
