# Generated by Django 4.2.23 on 2026-07-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_browserpushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='kind',
            field=models.CharField(choices=[('report_received', '举报已收到'), ('report_resolved', '举报已处理'), ('sanction_applied', '用户处置'), ('sanction_revoked', '处置解除'), ('appeal_submitted', '申诉已提交'), ('appeal_resolved', '申诉已处理'), ('new_comment', 'New comment'), ('comment_reply', 'Comment reply'), ('profile_liked', 'Profile liked'), ('new_follower', 'New follower'), ('new_message', 'New message'), ('note_copied', 'Note copied'), ('note_revision_restored', 'Note revision restored')], max_length=40, verbose_name='通知类型'),
        ),
    ]
