"""Compatibility exports for legacy decorator imports."""

from accounts.services import (
    get_param,
    get_request_data,
    require_2fa_verified,
    send_operation_2fa_email,
    verify_2fa_for_request,
    verify_backup_code_secure,
    verify_email_code_from_cache,
    verify_totp_with_replay_protection,
)
from core.utils.request_utils import get_client_ip
from vault.services import (
    DEVICE_FAIL_THRESHOLD,
    IP_FAIL_THRESHOLD,
    VAULT_ACCESS_WINDOW,
    VAULT_ALERT_THRESHOLD,
    VAULT_CAPTCHA_THRESHOLD,
    VAULT_DEVICE_FAIL_THRESHOLD,
    VAULT_DEVICE_LOCK_SECONDS,
    VAULT_IP_FAIL_THRESHOLD,
    VAULT_SESSION_ACCESS_WINDOW,
    VAULT_USER_FAIL_THRESHOLD,
    VAULT_USER_LOCK_SECONDS,
    check_and_ban_ip,
    check_vault_access,
    check_vault_locked,
    get_vault_access_key,
    get_vault_access_remaining,
    get_vault_fail_count,
    get_vault_fail_key,
    get_vault_lock_key,
    get_vault_user_fail_key,
    get_vault_user_lock_key,
    grant_vault_access,
    increment_vault_fail_count,
    is_vault_access_session_scoped,
    require_vault_access,
    reset_vault_fail_count,
    revoke_vault_access,
    send_vault_security_alert,
    verify_captcha_for_vault,
    verify_vault_2fa,
)
